// react/src/components/BX3Button.tsx
import React, { useState } from 'react';
import { useBX3Theme } from '../hooks/useBX3Theme';
import { BX3ButtonProps, BX3ButtonVariant } from '../types';

export const BX3Button: React.FC<BX3ButtonProps> = ({
  children,
  variant = BX3ButtonVariant.PRIMARY,
  size = 'md',
  loading = false,
  disabled = false,
  onClick,
  ...props
}) => {
  const { colors, isDark } = useBX3Theme();
  const [isHovered, setIsHovered] = useState(false);
  const [isPressed, setIsPressed] = useState(false);

  const getVariantStyles = () => {
    switch (variant) {
      case BX3ButtonVariant.PRIMARY:
        return {
          background: colors.primary,
          color: colors.onPrimary,
          border: 'none',
        };
      case BX3ButtonVariant.SECONDARY:
        return {
          background: colors.surface,
          color: colors.onSurface,
          border: `1px solid ${colors.onSurfaceVariant}`,
        };
      case BX3ButtonVariant.GHOST:
        return {
          background: 'transparent',
          color: colors.onSurface,
          border: 'none',
        };
      default:
        return {};
    }
  };

  const getSizeStyles = () => {
    switch (size) {
      case 'sm': return { padding: '8px 16px', fontSize: '12px' };
      case 'md': return { padding: '12px 24px', fontSize: '14px' };
      case 'lg': return { padding: '16px 32px', fontSize: '16px' };
      default: return {};
    }
  };

  const styles = {
    ...getVariantStyles(),
    ...getSizeStyles(),
    borderRadius: '8px',
    cursor: disabled ? 'not-allowed' : 'pointer',
    opacity: disabled ? 0.5 : 1,
    transition: 'all 0.2s ease',
    transform: isPressed ? 'scale(0.98)' : 'scale(1)',
    boxShadow: isHovered && !disabled ? `0 4px 12px ${colors.primary}40` : 'none',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  };

  return (
    <button
      style={styles}
      disabled={disabled || loading}
      onClick={onClick}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      onMouseDown={() => setIsPressed(true)}
      onMouseUp={() => setIsPressed(false)}
      {...props}
    >
      {loading && <BX3LoadingSpinner size="sm" />}
      {children}
    </button>
  );
};

// vue/src/components/BX3Button.vue
<template>
  <button
    :class="[
      'bx3-button',
      `bx3-button--${variant}`,
      `bx3-button--${size}`,
      {
        'bx3-button--loading': loading,
        'bx3-button--disabled': disabled,
        'bx3-button--hovered': isHovered,
        'bx3-button--pressed': isPressed,
      },
    ]"
    :disabled="disabled || loading"
    @click="handleClick"
    @mouseenter="isHovered = true"
    @mouseleave="isHovered = false"
    @mousedown="isPressed = true"
    @mouseup="isPressed = false"
  >
    <BX3LoadingSpinner v-if="loading" size="sm" />
    <slot />
  </button>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useBX3Theme } from '../composables/useBX3Theme';
import BX3LoadingSpinner from './BX3LoadingSpinner.vue';
import type { BX3ButtonVariant, BX3ButtonSize } from '../types';

interface Props {
  variant?: BX3ButtonVariant;
  size?: BX3ButtonSize;
  loading?: boolean;
  disabled?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'primary',
  size: 'md',
  loading: false,
  disabled: false,
});

const emit = defineEmits<{
  click: [event: MouseEvent];
}>();

const { colors, prefersReducedMotion } = useBX3Theme();

const isHovered = ref(false);
const isPressed = ref(false);

const handleClick = (event: MouseEvent) => {
  if (!props.disabled && !props.loading) {
    emit('click', event);
  }
};

const buttonStyles = computed(() => {
  const baseStyles = {
    borderRadius: '8px',
    cursor: props.disabled ? 'not-allowed' : 'pointer',
    opacity: props.disabled ? 0.5 : 1,
    transition: prefersReducedMotion.value ? 'none' : 'all 0.2s ease',
  };

  const variantStyles = {
    primary: {
      background: colors.value.primary,
      color: colors.value.onPrimary,
      border: 'none',
    },
    secondary: {
      background: colors.value.surface,
      color: colors.value.onSurface,
      border: `1px solid ${colors.value.onSurfaceVariant}`,
    },
    ghost: {
      background: 'transparent',
      color: colors.value.onSurface,
      border: 'none',
    },
  };

  const sizeStyles = {
    sm: { padding: '8px 16px', fontSize: '12px' },
    md: { padding: '12px 24px', fontSize: '14px' },
    lg: { padding: '16px 32px', fontSize: '16px' },
  };

  return {
    ...baseStyles,
    ...variantStyles[props.variant],
    ...sizeStyles[props.size],
  };
});
</script>

<style scoped>
.bx3-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  font-family: inherit;
  font-weight: 500;
  border: none;
  outline: none;
}

.bx3-button--hovered:not(.bx3-button--disabled) {
  box-shadow: 0 4px 12px rgba(123, 31, 162, 0.25);
}

.bx3-button--pressed:not(.bx3-button--disabled) {
  transform: scale(0.98);
}

.bx3-button--loading {
  cursor: wait;
}
</style>
